a=input("enter your name")
print("your name is",a)
print(5+7.8)
print(56+67)
print(24*98)
print("your name is",a)
b=int(input("enter a number:"))
c=input("enter your name")
print("your name is",a)
print("avg=",num+num+num)
